title: Hacker-Blog
description: "Random site I made."
author:
  name: "Shamus"
  email: "not your problem"
  url: "shamus118.github.io/hacker-blog"

baseurl: shamus118.github.io/hacker-blog

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Me"
year : "2019"
